<template>
    <div>
        <div style="width: 100%;height: 80px;background-color: #ccc;"></div>
        <ul class="ul" style="height: 500px;width: 100%;overflow-y: auto;">
            <li>
                <p>11</p>
            </li>
            <li>
                <p>21</p>
            </li>
            <li>
                <p>31</p>
            </li>
            <li>
                <p>41</p>
            </li>
            <li>
                <p>51</p>
            </li>
            <li>
                <p>61</p>
            </li>
            <li>
                <p>71</p>
            </li>
            <li>
                <p>81</p>
            </li>
            <li>
                <p>91</p>
            </li>
            <li>
                <p>101</p>
            </li>
            <li>
                <p>111</p>
            </li>
            <li>
                <p>121</p>
            </li>
            <li>
                <p>131</p>
            </li>
            <li>
                <p>141</p>
            </li>
            <li>
                <p>151</p>
            </li>
            <li>
                <p>161</p>
            </li>
            <li>
                <p>171</p>
            </li>
            <li>
                <p>181</p>
            </li>
            <li>
                <p>191</p>
            </li>
            <li>
                <p>201</p>
            </li>
            <li>
                <p>211</p>
            </li>
            <li>
                <p>221</p>
            </li>
            <li>
                <p>231</p>
            </li>
            <li>
                <p>241</p>
            </li>
            <li>
                <p>251</p>
            </li>
            <li>
                <p>261</p>
            </li>
            <li>
                <p>271</p>
            </li>
            <li>
                <p>281</p>
            </li>
            <li>
                <p>291</p>
            </li>
            <li>
                <p>301</p>
            </li>
            <li>
                <p>311</p>
            </li>
            <li>
                <p>321</p>
            </li>
            <li>
                <p>331</p>
            </li>
            <li>
                <p>341</p>
            </li>
            <li>
                <p>351</p>
            </li>
            <li>
                <p>361</p>
            </li>
            <li>
                <p>371</p>
            </li>
            <li>
                <p>381</p>
            </li>
            <li>
                <p>391</p>
            </li>
            <li>
                <p>401</p>
            </li>
            <li>
                <p>411</p>
            </li>
            <li>
                <p>421</p>
            </li>
            <li>
                <p>431</p>
            </li>
            <li>
                <p>441</p>
            </li>
            <li>
                <p>451</p>
            </li>
            <li>
                <p>461</p>
            </li>
            <li>
                <p>471</p>
            </li>
            <li>
                <p>481</p>
            </li>
            <li>
                <p>491</p>
            </li>
            <li>
                <p>501</p>
            </li>
            <li>
                <p>511</p>
            </li>
            <li>
                <p>521</p>
            </li>
            <li>
                <p>531</p>
            </li>
            <li>
                <p>541</p>
            </li>
            <li>
                <p>551</p>
            </li>
            <li>
                <p>561</p>
            </li>
            <li>
                <p>571</p>
            </li>
            <li>
                <p>581</p>
            </li>
            <li>
                <p>591</p>
            </li>
            <li>
                <p>601</p>
            </li>
            <li>
                <p>611</p>
            </li>
            <li>
                <p>621</p>
            </li>
            <li>
                <p>631</p>
            </li>
            <li>
                <p>641</p>
            </li>
            <li>
                <p>651</p>
            </li>
            <li>
                <p>661</p>
            </li>
            <li>
                <p>671</p>
            </li>
            <li>
                <p>681</p>
            </li>
            <li>
                <p>691</p>
            </li>
            <li>
                <p>701</p>
            </li>
            <li>
                <p>711</p>
            </li>
            <li>
                <p>721</p>
            </li>
            <li>
                <p>731</p>
            </li>
            <li>
                <p>741</p>
            </li>
            <li>
                <p>751</p>
            </li>
            <li>
                <p>761</p>
            </li>
            <li>
                <p>771</p>
            </li>
            <li>
                <p>781</p>
            </li>
            <li>
                <p>791</p>
            </li>
            <li>
                <p>801</p>
            </li>
            <li>
                <p>811</p>
            </li>
            <li>
                <p>821</p>
            </li>
            <li>
                <p>831</p>
            </li>
            <li>
                <p>841</p>
            </li>
            <li>
                <p>851</p>
            </li>
            <li>
                <p>861</p>
            </li>
            <li>
                <p>871</p>
            </li>
            <li>
                <p>881</p>
            </li>
            <li>
                <p>891</p>
            </li>
            <li>
                <p>901</p>
            </li>
            <li>
                <p>911</p>
            </li>
            <li>
                <p>921</p>
            </li>
            <li>
                <p>931</p>
            </li>
            <li>
                <p>941</p>
            </li>
            <li>
                <p>951</p>
            </li>
            <li>
                <p>961</p>
            </li>
            <li>
                <p>971</p>
            </li>
            <li>
                <p>981</p>
            </li>
            <li>
                <p>991</p>
            </li>
            <li>
                <p>1001</p>
            </li>
        </ul>
    </div>
</template>

<script>

    export default {
        data() {
            return {}
        },
        created() {
            console.log(window);
        },
        mounted() {
            var height = $(window).height();
            height = height - 80
            $('.ul').css({'height': height})

        }
    }

</script>

<style scoped>

</style>